// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bL_H
#define UNIQ_bL_H
#include "../../areuniq/5/areuniq57-58.h"
#define uniqenum58(ag,a,ai,b,aj,c,ak,d,al,e,am,f,an,g,ao,h,ap,i,aq,j,ar,k,as,l,at,m,au,n,av,o,aw,p,ax,q,ay,r,az,s,aA,t,aB,u,aC,v,aD,w,aE,x,aF,y,aG,z,aH,A,aI,B,aJ,C,aK,D,aL,E,aM,F,aN,G,aO,H,aP,I,aQ,J,aR,K,aS,L,aT,M,aU,N,aV,O,aW,P,aX,Q,aY,R,aZ,S,a_,T,a1,U,a2,V,a3,W,a4,X,a5,Y,a6,Z,a7,aa,a8,ab,a9,ac,a0,ad,ba,ae,bb,af,bc,ah)enum ag{a ai,b aj,c ak,d al,e am,f an,g ao,h ap,i aq,j ar,k as,l at,m au,n av,o aw,p ax,q ay,r az,s aA,t aB,u aC,v aD,w aE,x aF,y aG,z aH,A aI,B aJ,C aK,D aL,E aM,F aN,G aO,H aP,I aQ,J aR,K aS,L aT,M aU,N aV,O aW,P aX,Q aY,R aZ,S a_,T a1,U a2,V a3,W a4,X a5,Y a6,Z a7,aa a8,ab a9,ac a0,ad ba,ae bb,af bc}ah _UNIQA(58,ag,ah,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,aa,ab,ac,ad,ae,af)
#endif
