// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bD_H
#define UNIQ_bD_H
#include "../../areuniq/areuniq49-50.h"
#define uniqenum50(Y,a,aa,b,ab,c,ac,d,ad,e,ae,f,af,g,ag,h,ah,i,ai,j,aj,k,ak,l,al,m,am,n,an,o,ao,p,ap,q,aq,r,ar,s,as,t,at,u,au,v,av,w,aw,x,ax,y,ay,z,az,A,aA,B,aB,C,aC,D,aD,E,aE,F,aF,G,aG,H,aH,I,aI,J,aJ,K,aK,L,aL,M,aM,N,aN,O,aO,P,aP,Q,aQ,R,aR,S,aS,T,aT,U,aU,V,aV,W,aW,X,aX,Z)enum Y{a aa,b ab,c ac,d ad,e ae,f af,g ag,h ah,i ai,j aj,k ak,l al,m am,n an,o ao,p ap,q aq,r ar,s as,t at,u au,v av,w aw,x ax,y ay,z az,A aA,B aB,C aC,D aD,E aE,F aF,G aG,H aH,I aI,J aJ,K aK,L aL,M aM,N aN,O aO,P aP,Q aQ,R aR,S aS,T aT,U aU,V aV,W aW,X aX}Z _UNIQA(50,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X)
#endif
