// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_b_H
#define UNIQ_b_H
#define areuniq9(a,b,c,d,e,f,g,h,i)areuniq6(a,b,c,d,e,f)_UNIQJ areuniq6(a,b,c,g,h,i)_UNIQJ areuniq6(d,e,f,g,h,i)
#define areuniq10(a,b,c,d,e,f,g,h,i,j)areuniq7(a,b,c,d,e,f,g)_UNIQJ areuniq7(a,b,c,d,h,i,j)_UNIQJ areuniq6(e,f,g,h,i,j)
#define areuniq11(a,b,c,d,e,f,g,h,i,j,k)areuniq8(a,b,c,d,e,f,g,h)_UNIQJ areuniq7(a,b,c,d,i,j,k)_UNIQJ areuniq7(e,f,g,h,i,j,k)
#define areuniq12(a,b,c,d,e,f,g,h,i,j,k,l)areuniq8(a,b,c,d,e,f,g,h)_UNIQJ areuniq8(a,b,c,d,i,j,k,l)_UNIQJ areuniq8(e,f,g,h,i,j,k,l)
#define areuniq13(a,b,c,d,e,f,g,h,i,j,k,l,m)areuniq9(a,b,c,d,e,f,g,h,i)_UNIQJ areuniq9(a,b,c,d,e,j,k,l,m)_UNIQJ areuniq8(f,g,h,i,j,k,l,m)
#define areuniq14(a,b,c,d,e,f,g,h,i,j,k,l,m,n)areuniq10(a,b,c,d,e,f,g,h,i,j)_UNIQJ areuniq9(a,b,c,d,e,k,l,m,n)_UNIQJ areuniq9(f,g,h,i,j,k,l,m,n)
#define areuniq15(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o)areuniq10(a,b,c,d,e,f,g,h,i,j)_UNIQJ areuniq10(a,b,c,d,e,k,l,m,n,o)_UNIQJ areuniq10(f,g,h,i,j,k,l,m,n,o)
#endif
