// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_n_H
#define UNIQ_n_H
#include "3/areuniq32-34.h"
#define areuniq49(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W)areuniq33(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G)_UNIQJ areuniq33(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W)_UNIQJ areuniq32(r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W)
#define areuniq50(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X)areuniq34(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H)_UNIQJ areuniq33(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X)_UNIQJ areuniq33(r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X)
#endif
