// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_c_H
#define UNIQ_c_H
#include "areuniq9-15.h"
#define areuniq16(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)areuniq11(a,b,c,d,e,f,g,h,i,j,k)_UNIQJ areuniq11(a,b,c,d,e,f,l,m,n,o,p)_UNIQJ areuniq10(g,h,i,j,k,l,m,n,o,p)
#define areuniq17(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q)areuniq12(a,b,c,d,e,f,g,h,i,j,k,l)_UNIQJ areuniq11(a,b,c,d,e,f,m,n,o,p,q)_UNIQJ areuniq11(g,h,i,j,k,l,m,n,o,p,q)
#define areuniq18(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)areuniq12(a,b,c,d,e,f,g,h,i,j,k,l)_UNIQJ areuniq12(a,b,c,d,e,f,m,n,o,p,q,r)_UNIQJ areuniq12(g,h,i,j,k,l,m,n,o,p,q,r)
#define areuniq19(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s)areuniq13(a,b,c,d,e,f,g,h,i,j,k,l,m)_UNIQJ areuniq13(a,b,c,d,e,f,g,n,o,p,q,r,s)_UNIQJ areuniq12(h,i,j,k,l,m,n,o,p,q,r,s)
#define areuniq20(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t)areuniq14(a,b,c,d,e,f,g,h,i,j,k,l,m,n)_UNIQJ areuniq13(a,b,c,d,e,f,g,o,p,q,r,s,t)_UNIQJ areuniq13(h,i,j,k,l,m,n,o,p,q,r,s,t)
#endif
