// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bm_H
#define UNIQ_bm_H
#include "../../areuniq/areuniq29-31.h"
#define uniqenum30(E,a,G,b,H,c,I,d,J,e,K,f,L,g,M,h,N,i,O,j,P,k,Q,l,R,m,S,n,T,o,U,p,V,q,W,r,X,s,Y,t,Z,u,aa,v,ab,w,ac,x,ad,y,ae,z,af,A,ag,B,ah,C,ai,D,aj,F)enum E{a G,b H,c I,d J,e K,f L,g M,h N,i O,j P,k Q,l R,m S,n T,o U,p V,q W,r X,s Y,t Z,u aa,v ab,w ac,x ad,y ae,z af,A ag,B ah,C ai,D aj}F _UNIQA(30,E,F,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D)
#define uniqenum31(F,a,H,b,I,c,J,d,K,e,L,f,M,g,N,h,O,i,P,j,Q,k,R,l,S,m,T,n,U,o,V,p,W,q,X,r,Y,s,Z,t,aa,u,ab,v,ac,w,ad,x,ae,y,af,z,ag,A,ah,B,ai,C,aj,D,ak,E,al,G)enum F{a H,b I,c J,d K,e L,f M,g N,h O,i P,j Q,k R,l S,m T,n U,o V,p W,q X,r Y,s Z,t aa,u ab,v ac,w ad,x ae,y af,z ag,A ah,B ai,C aj,D ak,E al}G _UNIQA(31,F,G,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E)
#endif
