// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bo_H
#define UNIQ_bo_H
#include "../../areuniq/3/areuniq32-34.h"
#include "../../areuniq/3/areuniq35-37.h"
#define uniqenum34(I,a,K,b,L,c,M,d,N,e,O,f,P,g,Q,h,R,i,S,j,T,k,U,l,V,m,W,n,X,o,Y,p,Z,q,aa,r,ab,s,ac,t,ad,u,ae,v,af,w,ag,x,ah,y,ai,z,aj,A,ak,B,al,C,am,D,an,E,ao,F,ap,G,aq,H,ar,J)enum I{a K,b L,c M,d N,e O,f P,g Q,h R,i S,j T,k U,l V,m W,n X,o Y,p Z,q aa,r ab,s ac,t ad,u ae,v af,w ag,x ah,y ai,z aj,A ak,B al,C am,D an,E ao,F ap,G aq,H ar}J _UNIQA(34,I,J,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H)
#define uniqenum35(J,a,L,b,M,c,N,d,O,e,P,f,Q,g,R,h,S,i,T,j,U,k,V,l,W,m,X,n,Y,o,Z,p,aa,q,ab,r,ac,s,ad,t,ae,u,af,v,ag,w,ah,x,ai,y,aj,z,ak,A,al,B,am,C,an,D,ao,E,ap,F,aq,G,ar,H,as,I,at,K)enum J{a L,b M,c N,d O,e P,f Q,g R,h S,i T,j U,k V,l W,m X,n Y,o Z,p aa,q ab,r ac,s ad,t ae,u af,v ag,w ah,x ai,y aj,z ak,A al,B am,C an,D ao,E ap,F aq,G ar,H as,I at}K _UNIQA(35,J,K,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I)
#endif
