// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_br_H
#define UNIQ_br_H
#include "../../areuniq/areuniq38-40.h"
#define uniqenum38(M,a,O,b,P,c,Q,d,R,e,S,f,T,g,U,h,V,i,W,j,X,k,Y,l,Z,m,aa,n,ab,o,ac,p,ad,q,ae,r,af,s,ag,t,ah,u,ai,v,aj,w,ak,x,al,y,am,z,an,A,ao,B,ap,C,aq,D,ar,E,as,F,at,G,au,H,av,I,aw,J,ax,K,ay,L,az,N)enum M{a O,b P,c Q,d R,e S,f T,g U,h V,i W,j X,k Y,l Z,m aa,n ab,o ac,p ad,q ae,r af,s ag,t ah,u ai,v aj,w ak,x al,y am,z an,A ao,B ap,C aq,D ar,E as,F at,G au,H av,I aw,J ax,K ay,L az}N _UNIQA(38,M,N,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)
#endif
