// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bq_H
#define UNIQ_bq_H
#include "../../areuniq/3/areuniq35-37.h"
#define uniqenum37(L,a,N,b,O,c,P,d,Q,e,R,f,S,g,T,h,U,i,V,j,W,k,X,l,Y,m,Z,n,aa,o,ab,p,ac,q,ad,r,ae,s,af,t,ag,u,ah,v,ai,w,aj,x,ak,y,al,z,am,A,an,B,ao,C,ap,D,aq,E,ar,F,as,G,at,H,au,I,av,J,aw,K,ax,M)enum L{a N,b O,c P,d Q,e R,f S,g T,h U,i V,j W,k X,l Y,m Z,n aa,o ab,p ac,q ad,r ae,s af,t ag,u ah,v ai,w aj,x ak,y al,z am,A an,B ao,C ap,D aq,E ar,F as,G at,H au,I av,J aw,K ax}M _UNIQA(37,L,M,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K)
#endif
