// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bp_H
#define UNIQ_bp_H
#include "../../areuniq/3/areuniq35-37.h"
#define uniqenum36(K,a,M,b,N,c,O,d,P,e,Q,f,R,g,S,h,T,i,U,j,V,k,W,l,X,m,Y,n,Z,o,aa,p,ab,q,ac,r,ad,s,ae,t,af,u,ag,v,ah,w,ai,x,aj,y,ak,z,al,A,am,B,an,C,ao,D,ap,E,aq,F,ar,G,as,H,at,I,au,J,av,L)enum K{a M,b N,c O,d P,e Q,f R,g S,h T,i U,j V,k W,l X,m Y,n Z,o aa,p ab,q ac,r ad,s ae,t af,u ag,v ah,w ai,x aj,y ak,z al,A am,B an,C ao,D ap,E aq,F ar,G as,H at,I au,J av}L _UNIQA(36,K,L,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J)
#endif
