// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bn_H
#define UNIQ_bn_H
#include "../../areuniq/3/areuniq32-34.h"
#define uniqenum32(G,a,I,b,J,c,K,d,L,e,M,f,N,g,O,h,P,i,Q,j,R,k,S,l,T,m,U,n,V,o,W,p,X,q,Y,r,Z,s,aa,t,ab,u,ac,v,ad,w,ae,x,af,y,ag,z,ah,A,ai,B,aj,C,ak,D,al,E,am,F,an,H)enum G{a I,b J,c K,d L,e M,f N,g O,h P,i Q,j R,k S,l T,m U,n V,o W,p X,q Y,r Z,s aa,t ab,u ac,v ad,w ae,x af,y ag,z ah,A ai,B aj,C ak,D al,E am,F an}H _UNIQA(32,G,H,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F)
#define uniqenum33(H,a,J,b,K,c,L,d,M,e,N,f,O,g,P,h,Q,i,R,j,S,k,T,l,U,m,V,n,W,o,X,p,Y,q,Z,r,aa,s,ab,t,ac,u,ad,v,ae,w,af,x,ag,y,ah,z,ai,A,aj,B,ak,C,al,D,am,E,an,F,ao,G,ap,I)enum H{a J,b K,c L,d M,e N,f O,g P,h Q,i R,j S,k T,l U,m V,n W,o X,p Y,q Z,r aa,s ab,t ac,u ad,v ae,w af,x ag,y ah,z ai,A aj,B ak,C al,D am,E an,F ao,G ap}I _UNIQA(33,H,I,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G)
#endif
