// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bk_H
#define UNIQ_bk_H
#include "../../areuniq/2/areuniq25-28.h"
#define uniqenum26(A,a,C,b,D,c,E,d,F,e,G,f,H,g,I,h,J,i,K,j,L,k,M,l,N,m,O,n,P,o,Q,p,R,q,S,r,T,s,U,t,V,u,W,v,X,w,Y,x,Z,y,aa,z,ab,B)enum A{a C,b D,c E,d F,e G,f H,g I,h J,i K,j L,k M,l N,m O,n P,o Q,p R,q S,r T,s U,t V,u W,v X,w Y,x Z,y aa,z ab}B _UNIQA(26,A,B,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
#define uniqenum27(B,a,D,b,E,c,F,d,G,e,H,f,I,g,J,h,K,i,L,j,M,k,N,l,O,m,P,n,Q,o,R,p,S,q,T,r,U,s,V,t,W,u,X,v,Y,w,Z,x,aa,y,ab,z,ac,A,ad,C)enum B{a D,b E,c F,d G,e H,f I,g J,h K,i L,j M,k N,l O,m P,n Q,o R,p S,q T,r U,s V,t W,u X,v Y,w Z,x aa,y ab,z ac,A ad}C _UNIQA(27,B,C,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A)
#endif
