// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bj_H
#define UNIQ_bj_H
#include "../../areuniq/2/areuniq21-24.h"
#include "../../areuniq/2/areuniq25-28.h"
#define uniqenum24(y,a,A,b,B,c,C,d,D,e,E,f,F,g,G,h,H,i,I,j,J,k,K,l,L,m,M,n,N,o,O,p,P,q,Q,r,R,s,S,t,T,u,U,v,V,w,W,x,X,z)enum y{a A,b B,c C,d D,e E,f F,g G,h H,i I,j J,k K,l L,m M,n N,o O,p P,q Q,r R,s S,t T,u U,v V,w W,x X}z _UNIQA(24,y,z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x)
#define uniqenum25(z,a,B,b,C,c,D,d,E,e,F,f,G,g,H,h,I,i,J,j,K,k,L,l,M,m,N,n,O,o,P,p,Q,q,R,r,S,s,T,t,U,u,V,v,W,w,X,x,Y,y,Z,A)enum z{a B,b C,c D,d E,e F,f G,g H,h I,i J,j K,k L,l M,m N,n O,o P,p Q,q R,r S,s T,t U,u V,v W,w X,x Y,y Z}A _UNIQA(25,z,A,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y)
#endif
