// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_b3_H
#define UNIQ_b3_H
#include "../../areuniq/7/areuniq76.h"
#define uniqenum76(ay,a,aA,b,aB,c,aC,d,aD,e,aE,f,aF,g,aG,h,aH,i,aI,j,aJ,k,aK,l,aL,m,aM,n,aN,o,aO,p,aP,q,aQ,r,aR,s,aS,t,aT,u,aU,v,aV,w,aW,x,aX,y,aY,z,aZ,A,a_,B,a1,C,a2,D,a3,E,a4,F,a5,G,a6,H,a7,I,a8,J,a9,K,a0,L,ba,M,bb,N,bc,O,bd,P,be,Q,bf,R,bg,S,bh,T,bi,U,bj,V,bk,W,bl,X,bm,Y,bn,Z,bo,aa,bp,ab,bq,ac,br,ad,bs,ae,bt,af,bu,ag,bv,ah,bw,ai,bx,aj,by,ak,bz,al,bA,am,bB,an,bC,ao,bD,ap,bE,aq,bF,ar,bG,as,bH,at,bI,au,bJ,av,bK,aw,bL,ax,bM,az)enum ay{a aA,b aB,c aC,d aD,e aE,f aF,g aG,h aH,i aI,j aJ,k aK,l aL,m aM,n aN,o aO,p aP,q aQ,r aR,s aS,t aT,u aU,v aV,w aW,x aX,y aY,z aZ,A a_,B a1,C a2,D a3,E a4,F a5,G a6,H a7,I a8,J a9,K a0,L ba,M bb,N bc,O bd,P be,Q bf,R bg,S bh,T bi,U bj,V bk,W bl,X bm,Y bn,Z bo,aa bp,ab bq,ac br,ad bs,ae bt,af bu,ag bv,ah bw,ai bx,aj by,ak bz,al bA,am bB,an bC,ao bD,ap bE,aq bF,ar bG,as bH,at bI,au bJ,av bK,aw bL,ax bM}az _UNIQA(76,ay,az,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,aa,ab,ac,ad,ae,af,ag,ah,ai,aj,ak,al,am,an,ao,ap,aq,ar,as,at,au,av,aw,ax)
#endif
