// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_g_H
#define UNIQ_g_H
#include "../2/areuniq21-24.h"
#define areuniq32(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F)areuniq22(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v)_UNIQJ areuniq21(a,b,c,d,e,f,g,h,i,j,k,w,x,y,z,A,B,C,D,E,F)_UNIQJ areuniq21(l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F)
#define areuniq33(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G)areuniq22(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v)_UNIQJ areuniq22(a,b,c,d,e,f,g,h,i,j,k,w,x,y,z,A,B,C,D,E,F,G)_UNIQJ areuniq22(l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G)
#define areuniq34(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H)areuniq23(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w)_UNIQJ areuniq23(a,b,c,d,e,f,g,h,i,j,k,l,x,y,z,A,B,C,D,E,F,G,H)_UNIQJ areuniq22(m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H)
#endif
