// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bg_H
#define UNIQ_bg_H
#include "../../areuniq/areuniq9-15.h"
#include "../../areuniq/areuniq16-20.h"
#define uniqenum14(o,a,q,b,r,c,s,d,t,e,u,f,v,g,w,h,x,i,y,j,z,k,A,l,B,m,C,n,D,p)enum o{a q,b r,c s,d t,e u,f v,g w,h x,i y,j z,k A,l B,m C,n D}p _UNIQA(14,o,p,a,b,c,d,e,f,g,h,i,j,k,l,m,n)
#define uniqenum15(p,a,r,b,s,c,t,d,u,e,v,f,w,g,x,h,y,i,z,j,A,k,B,l,C,m,D,n,E,o,F,q)enum p{a r,b s,c t,d u,e v,f w,g x,h y,i z,j A,k B,l C,m D,n E,o F}q _UNIQA(15,p,q,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o)
#define uniqenum16(q,a,s,b,t,c,u,d,v,e,w,f,x,g,y,h,z,i,A,j,B,k,C,l,D,m,E,n,F,o,G,p,H,r)enum q{a s,b t,c u,d v,e w,f x,g y,h z,i A,j B,k C,l D,m E,n F,o G,p H}r _UNIQA(16,q,r,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)
#define uniqenum17(r,a,t,b,u,c,v,d,w,e,x,f,y,g,z,h,A,i,B,j,C,k,D,l,E,m,F,n,G,o,H,p,I,q,J,s)enum r{a t,b u,c v,d w,e x,f y,g z,h A,i B,j C,k D,l E,m F,n G,o H,p I,q J}s _UNIQA(17,r,s,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q)
#endif
