// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_e_H
#define UNIQ_e_H
#include "../areuniq16-20.h"
#define areuniq25(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y)areuniq17(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q)_UNIQJ areuniq17(a,b,c,d,e,f,g,h,i,r,s,t,u,v,w,x,y)_UNIQJ areuniq16(j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y)
#define areuniq26(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)areuniq18(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)_UNIQJ areuniq17(a,b,c,d,e,f,g,h,i,s,t,u,v,w,x,y,z)_UNIQJ areuniq17(j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
#define areuniq27(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A)areuniq18(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)_UNIQJ areuniq18(a,b,c,d,e,f,g,h,i,s,t,u,v,w,x,y,z,A)_UNIQJ areuniq18(j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A)
#define areuniq28(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B)areuniq19(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s)_UNIQJ areuniq19(a,b,c,d,e,f,g,h,i,j,t,u,v,w,x,y,z,A,B)_UNIQJ areuniq18(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B)
#endif
