// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_d_H
#define UNIQ_d_H
#include "../areuniq9-15.h"
#include "../areuniq16-20.h"
#define areuniq21(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u)areuniq14(a,b,c,d,e,f,g,h,i,j,k,l,m,n)_UNIQJ areuniq14(a,b,c,d,e,f,g,o,p,q,r,s,t,u)_UNIQJ areuniq14(h,i,j,k,l,m,n,o,p,q,r,s,t,u)
#define areuniq22(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v)areuniq15(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o)_UNIQJ areuniq15(a,b,c,d,e,f,g,h,p,q,r,s,t,u,v)_UNIQJ areuniq14(i,j,k,l,m,n,o,p,q,r,s,t,u,v)
#define areuniq23(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w)areuniq16(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)_UNIQJ areuniq15(a,b,c,d,e,f,g,h,q,r,s,t,u,v,w)_UNIQJ areuniq15(i,j,k,l,m,n,o,p,q,r,s,t,u,v,w)
#define areuniq24(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x)areuniq16(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)_UNIQJ areuniq16(a,b,c,d,e,f,g,h,q,r,s,t,u,v,w,x)_UNIQJ areuniq16(i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x)
#endif
