// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bw_H
#define UNIQ_bw_H
#include "../../areuniq/4/areuniq43-44.h"
#define uniqenum43(R,a,T,b,U,c,V,d,W,e,X,f,Y,g,Z,h,aa,i,ab,j,ac,k,ad,l,ae,m,af,n,ag,o,ah,p,ai,q,aj,r,ak,s,al,t,am,u,an,v,ao,w,ap,x,aq,y,ar,z,as,A,at,B,au,C,av,D,aw,E,ax,F,ay,G,az,H,aA,I,aB,J,aC,K,aD,L,aE,M,aF,N,aG,O,aH,P,aI,Q,aJ,S)enum R{a T,b U,c V,d W,e X,f Y,g Z,h aa,i ab,j ac,k ad,l ae,m af,n ag,o ah,p ai,q aj,r ak,s al,t am,u an,v ao,w ap,x aq,y ar,z as,A at,B au,C av,D aw,E ax,F ay,G az,H aA,I aB,J aC,K aD,L aE,M aF,N aG,O aH,P aI,Q aJ}S _UNIQA(43,R,S,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q)
#endif
