// Code generated by uniqenum. DO NOT EDIT.
#ifndef UNIQ_bv_H
#define UNIQ_bv_H
#include "../../areuniq/4/areuniq41-42.h"
#define uniqenum42(Q,a,S,b,T,c,U,d,V,e,W,f,X,g,Y,h,Z,i,aa,j,ab,k,ac,l,ad,m,ae,n,af,o,ag,p,ah,q,ai,r,aj,s,ak,t,al,u,am,v,an,w,ao,x,ap,y,aq,z,ar,A,as,B,at,C,au,D,av,E,aw,F,ax,G,ay,H,az,I,aA,J,aB,K,aC,L,aD,M,aE,N,aF,O,aG,P,aH,R)enum Q{a S,b T,c U,d V,e W,f X,g Y,h Z,i aa,j ab,k ac,l ad,m ae,n af,o ag,p ah,q ai,r aj,s ak,t al,u am,v an,w ao,x ap,y aq,z ar,A as,B at,C au,D av,E aw,F ax,G ay,H az,I aA,J aB,K aC,L aD,M aE,N aF,O aG,P aH}R _UNIQA(42,Q,R,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P)
#endif
